### PR TITLE
Rails 5 capability

### PR DESCRIPTION
**Pull request by kirs**
@phoet thank you for the gem.
I'm preparing an app upgrade to Rails 5 and `partially_useful` is one of the gems we use.

cc @rafaelfranca

### CODE REVIEW

**Comment by rafaelfranca** [comment]
:+1:

**Comment by phoet** [comment]
@kirs thank you for taking care of this.

it looks like there is some dependency issue here though, travis fails with this:

```
Gem::InstallError: rack requires Ruby version >= 2.2.2.
Using loofah 2.0.3
Gem::InstallError: activesupport requires Ruby version >= 2.2.2.
An error occurred while installing rack (2.0.0.rc1), and Bundler cannot
continue.
Make sure that `gem install rack -v '2.0.0.rc1'` succeeds before bundling.
```

if you like to take care of this gem, i can grant you contributor access to the repository and gem owner access.

**Comment by kirs** [comment]
Oh yeah. Rails 5 required Ruby >= 2.2. 
That means we would need to drop Travis support for 1.9.3, 2.0, 2.1 and add 2.2 and 2.3. Are you ok with this change?

**Comment by phoet** [comment]
Sure, new mayor version and all is good

Kir Shatrov <notifications@github.com> schrieb am Fr., 17. Juni 2016, 18:57:

**Comment by celsodantas** [comment]
ignore me, I'm here to just say <3 @phoet

**Comment by phoet** [comment]
@celsodantas 😽

**Comment by phoet** [comment]
released a new version 5.0.0 https://rubygems.org/gems/partially_useful/versions/5.0.0

**Comment by kirs** [comment]
Thanks!

**Pull request merged**
